### ISSUE TITLE
Cloud flaky test runner failing to load security service

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1000]
Reported by @kertal. 

Test run is failing: https://internal-ci.elastic.co/job/elastic+estf-cloud-kibana-flaky-test-runner/281/ 

Stack Trace: 

```
EST_CLOUD=1 TEST_KIBANA_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.kb.europe-west1.gcp.cloud.es.io:9243 TEST_ES_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.es.europe-west1.gcp.cloud.es.io:9243 node ./scripts/functional_test_runner.js --grep='should break text on newlines'
 debg Loading config file from "/Users/matthiaswilhelm/projects/kibana/test/functional/config.js"
 debg Loading config file from "/Users/matthiaswilhelm/projects/kibana/test/common/config.js"
 info Config loaded
--- Running test/functional/config.js
 debg randomness seed: 1631025413387
 debg [webdriver] Creating session
 warn Failure loading service "security"
ERROR Error: Request failed with status code 401
          at createError (/Users/matthiaswilhelm/projects/kibana/node_modules/axios/lib/core/createError.js:16:15)
          at settle (/Users/matthiaswilhelm/projects/kibana/node_modules/axios/lib/core/settle.js:17:12)
          at IncomingMessage.handleStreamEnd (/Users/matthiaswilhelm/projects/kibana/node_modules/axios/lib/adapters/http.js:260:11)
          at IncomingMessage.emit (events.js:412:35)
          at endReadableNT (internal/streams/readable.js:1317:12)
          at processTicksAndRejections (internal/process/task_queues.js:82:21)
 info Remote initialized: chrome 92.0.4515.159, collectingCoverage=false
 info chromedriver version: 92.0.4515.107 (87a818b10553a07434ea9e2b6dccf3cbe7895134-refs/branch-heads/4515@{#1634})
ERROR Error: Failure initializing 1 service(s)
          at ProviderCollection.loadAll (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/test/target_node/functional_test_runner/lib/providers/provider_collection.js:66:13)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at /Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/test/target_node/functional_test_runner/functional_test_runner.js:45:7
          at FunctionalTestRunner._run (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/test/target_node/functional_test_runner/functional_test_runner.js:109:14)
          at FunctionalTestRunner.run (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/test/target_node/functional_test_runner/functional_test_runner.js:41:12)
          at log.defaultLevel (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/test/target_node/functional_test_runner/cli.js:101:30)
          at /Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/dev-utils/target_node/run/run.js:59:7
          at withProcRunner (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/dev-utils/target_node/proc_runner/with_proc_runner.js:31:5)
          at run (/Users/matthiaswilhelm/projects/kibana/node_modules/@kbn/dev-utils/target_node/run/run.js:58:5)
```

Appears to also fail manually.  Step to reproduce: 

```
TEST_CLOUD=1 TEST_KIBANA_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.kb.europe-west1.gcp.cloud.es.io:9243 TEST_ES_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.es.europe-west1.gcp.cloud.es.io:9243 node ./scripts/functional_test_runner.js --grep='should break text on newlines'
```

**Comment by liza-mae** [comment]
Also reported by @poffdeluxe today, I believe this is an FTR issue.  Poff can you also add how you are manually running these?

**Comment by poffdeluxe** [comment]
Attempted to run with:
```
export TEST_KIBANA_URL=https://elastic:66qQh4hblFHFRuglbLzrbnso@a8b95573fdc343eb98340900ea4b5284.us-central1.gcp.foundit.no:9243
export TEST_ES_URL=https://elastic:66qQh4hblFHFRuglbLzrbnso@c58fb7afd9b64e178eecf0ef11f2ead5.us-central1.gcp.foundit.no:9243
ODE_TLS_REJECT_UNAUTHORIZED=0 node --no-warnings scripts/functional_test_runner --exclude-tag skipCloud
```

**Comment by liza-mae** [comment]
@kertal your manual failure is because your password is incorrect. 
```
TEST_CLOUD=1 TEST_KIBANA_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.kb.europe-west1.gcp.cloud.es.io:9243 TEST_ES_URL=https://elastic:v5FBwh7lyBMq7oEPpEMQn57Z@testing-772379.es.europe-west1.gcp.cloud.es.io:9243 node ./scripts/functional_test_runner.js --grep='should break text on newlines'
```

If you fix the password the test should run.

**Comment by liza-mae** [comment]
@poffdeluxe your manual failure appears to be a mismatch between the kibana branch and cloud version, if you run against 7.15 cloud, you need to be on kibana 7.15 branch.

**Comment by liza-mae** [comment]
@kertal as far as the flaky test runner issue, looks like something changed recently in the functional test runner.  It appears to impact master branch which is why you see it failing on your PR  https://github.com/elastic/kibana/pull/111284 (side note: I tested your PR manually on cloud using 7.15 branch and it is passed).  So far, latest 7.15 branch is not impacted.  I have not tried latest 7.x branch.  

I went back to Sept 2 commit on master and it works, so something changed after that.   We will have to check with kibana ops team if they know what changed.  cc @spalger

**Comment by liza-mae** [comment]
I found the commit that is causing the problem, api/status has changed format here: https://github.com/elastic/kibana/pull/110830, but it does not appear to work on 8.0 snapshot of cloud either.  

I will file an issue in kibana repo so someone from kibana ops can take a look.

**Comment by liza-mae** [comment]
Looks like all the issues raised have been resolved.  Closing.
