### ISSUE TITLE
[Upgrade] Reporting tests are failing

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#1199]
The upgrade reporting tests are failing recently, this issue describes the errors, fixes and analysis.

1. **[FIXED]** ```FTR terminates with unhandled promise rejection``` caused by socket hang up.  This was fixed by Spencer in https://github.com/elastic/kibana/pull/128309 to handle the error and keep the FTR from terminating.

```
10:11:38       └-> name ecommerce type png
10:11:38         └-> "before each" hook: global before each for "name ecommerce type png"
10:11:38         └-> "before each" hook for "name ecommerce type png"
10:11:55 Unhandled Promise rejection detected:
10:11:55 
10:11:55 Error: socket hang up
10:11:55    at connResetException (node:internal/errors:691:14)
10:11:55    at TLSSocket.socketOnEnd (node:_http_client:471:23)
10:11:55    at TLSSocket.emit (node:events:402:35)
10:11:55    at endReadableNT (node:internal/streams/readable:1343:12)
10:11:55    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
10:11:55  code: 'ECONNRESET',
10:11:55  response: undefined
10:11:55 }
10:11:55 
10:11:55 Terminating process...
```

2. **[OPEN]** ```Socket hang up fails reporting test```

```
 debg ReportingAPI.postJob(/api/reporting/generate/printablePdfV2?jobParams=%28browserTimezone%3AUTC%2Clayout%3A%28dimensions%3A%28height%3A2052%2Cwidth%3A1522.4000244140625%29%2Cid%3Aprint%29%2ClocatorParams%3A%21%28%28id%3ADASHBOARD_APP_LOCATOR%2Cparams%3A%28dashboardId%3A%27722b74f0-b882-11e8-a6d9-e546fe2bba5f%27%2CpreserveSavedFilters%3A%21t%2CtimeRange%3A%28from%3Anow-7d%2Cto%3Anow%29%2CuseHash%3A%21f%2CviewMode%3Aview%29%2Cversion%3A%278.1.1%27%29%29%2CobjectType%3Adashboard%2Ctitle%3A%27%5BeCommerce%5D%20Revenue%20Dashboard%27%2Cversion%3A%278.1.1%27%29)
         │ debg Waiting up to 60000ms for job /api/reporting/jobs/download/l158u7he000hd16a96deqtzf finished...
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg Report at path /api/reporting/jobs/download/l158u7he000hd16a96deqtzf is pending
         │ debg --- retry.waitForWithTimeout error: socket hang up
```

3. **[FIXED]**  ```waitForJobToFinish times out and fails reporting test.```  The default API timeout is 60 seconds but the UI timeout is 120 seconds, these should match and should be fixed by https://github.com/elastic/kibana/pull/128536

```
12:52:10          │ debg Waiting up to 60000ms for job /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz finished...
12:52:10          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:11          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:12          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:12          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:13          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:14          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:14          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:15          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:16          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:16          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:17          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:17          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:18          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:19          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:19          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:20          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:21          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:21          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:22          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:23          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:23          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:24          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:25          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:25          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:26          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:27          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:28          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:28          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:29          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:30          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:30          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:31          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:32          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:32          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:33          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:34          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:34          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:35          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:36          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:36          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:37          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:38          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:38          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:39          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:40          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:40          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:41          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:42          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:42          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:43          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:44          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:44          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:45          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:46          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:46          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:47          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:48          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:48          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:49          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:49          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:50          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:51          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:52          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:52          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:53          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:54          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:54          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:55          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:55          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:56          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:57          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:58          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:58          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:52:59          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:00          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:00          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:01          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:02          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:02          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:03          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:04          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:04          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:05          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:05          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:06          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:07          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:08          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:08          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:09          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:10          │ debg Report at path /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz is pending
12:53:10          │ info Taking screenshot "/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/functional/screenshots/failure/upgrade reporting smoke tests generate report space default name flights type pdf_optimize.png"
12:53:10          │ info Current URL is: https://8b8eed7fdcb14cacbbdd95949bc78ccd.us-east-1.aws.staging.foundit.no:9243/app/dashboards#/view/7adfa750-4c81-11e8-b3d7-01146121b73d?_g=(filters:!(),refreshInterval:(pause:!f,value:900000),time:(from:now-24h,to:now))
12:53:10          │ info Saving page source to: /var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/functional/failure_debug/html/upgrade reporting smoke tests generate report space default name flights type pdf_optimize.html
12:53:11          └- ✖ fail: upgrade reporting smoke tests generate report space default name flights type pdf_optimize
12:53:11          │      Error: timed out waiting for job /api/reporting/jobs/download/l13xa7fu000wd07c27fhargz finished
12:53:11          │       at onFailure (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_truthy.ts:39:13)
12:53:11          │       at retryForSuccess (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_success.ts:59:13)
12:53:11          │       at retryForTruthy (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_truthy.ts:27:3)
12:53:11          │       at RetryService.waitForWithTimeout (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry.ts:45:5)
12:53:11          │       at Object.waitForJobToFinish (test/upgrade/reporting_services.ts:54:7)
12:53:11          │       at /var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/upgrade/reporting_services.ts:83:11
12:53:11          │       at async Promise.all (index 0)
12:53:11          │       at Object.expectAllJobsToFinishSuccessfully (test/upgrade/reporting_services.ts:81:7)
12:53:11          │       at Context.<anonymous> (test/upgrade/apps/reporting/reporting_smoke_tests.ts:92:13)
12:53:11          │       at Object.apply (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1b/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/test/target_node/functional_test_runner/lib/mocha/wrap_function.js:87:16)
```

**Comment by liza-mae** [comment]
All the kibana core tests were passing on March 15, 2022, I expect something broke in staging environment. 

![Screenshot from 2022-03-28 09-40-33](https://user-images.githubusercontent.com/23424008/160455156-e3bd4aef-5b3d-4b5a-9c6c-c139b69e5c89.png)

**Comment by liza-mae** [comment]
Reporting was still passing in run #192 on March 18.   The issue started with run #193 on March 19, so I think it confirms this is a staging issue, since no code changes were made in Kibana I was using same released version both runs.

**Comment by liza-mae** [comment]
So I looked into the ```socket hang up``` issue, with the reporting team and cloud team, and although we still don't know the root cause, I still suspect something on cloud, not specific to staging.  

Anyway, I was able to patch the test using a try/catch around the code that waits for the reporting job to finish.  Since there is a verification step after this block of code, the test will still fail if the job truly did not finish, so it's better than the test aborting with socket hang up and we can reduce the test failures until we know root cause. 

```
 │ debg Report at path /api/reporting/jobs/download/l29euawe000i2786cb3wv926 is pending
         │ debg Report at path /api/reporting/jobs/download/l29euawe000i2786cb3wv926 is pending
         │ debg Report at path /api/reporting/jobs/download/l29euawe000i2786cb3wv926 is pending
         │ debg Report at path /api/reporting/jobs/download/l29euawe000i2786cb3wv926 is pending
         │ debg Report at path /api/reporting/jobs/download/l29euawe000i2786cb3wv926 is pending
         │ debg --- retry.waitForWithTimeout error: socket hang up
         │ debg Error waiting for job to finish: Error: timed out waiting for job /api/reporting/jobs/download/l29euawe000i2786cb3wv926 finished -- last error: Error: socket hang up
         │          at connResetException (node:internal/errors:691:14)
         │          at TLSSocket.socketOnEnd (node:_http_client:466:23)
         │          at TLSSocket.emit (node:events:538:35)
         │          at endReadableNT (node:internal/streams/readable:1345:12)
         │          at processTicksAndRejections (node:internal/process/task_queues:83:21)
         └- ✓ pass  (2.0m)
```
