### ISSUE TITLE
ESTF Cloud Jenkins job failing due to token timeout

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#23]
I am getting the following error on the cloud cluster cleanup script when running the Kibana tests.  After some further investigation the problem is most likely due to the vault token expiring by the time the test reaches cleanup point (the kibana tests run about an hour).  The vault token currently is done as part of the Jenkins job at the beginning, so either I need to move that into ESTF Gradle script or maybe start a cleanup job instead.  May talk with infra also see if they have any recommendations. 

22:19:51 Execution failed for task ':cleanup_kibana'.
22:19:51 > java.lang.Exception: Traceback (most recent call last):
22:19:51     File "/var/lib/jenkins/workspace/elastic+estf-cloud-kibana+master/scripts/python/cloud_cluster.py", line 244, in <module>
22:19:51       main(sys.argv[1:])
22:19:51 2 actionable tasks: 2 executed
22:19:51     File "/var/lib/jenkins/workspace/elastic+estf-cloud-kibana+master/scripts/python/cloud_cluster.py", line 239, in main
22:19:51       cluster = CloudCluster()
22:19:51     File "/var/lib/jenkins/workspace/elastic+estf-cloud-kibana+master/scripts/python/cloud_cluster.py", line 46, in __init__
22:19:51       print(username)
22:19:51   UnboundLocalError: local variable 'username' referenced before assignment

**Comment by liza-mae** [comment]
Infra fixed this issue with vault token by increasing expiration timeout
