### ISSUE TITLE
Fix upgrade Kibana functional test failures

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#903]
Investigate and fix upgrade functional test failures on 7.13.0

### Jenkins Job Report 

https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/101/testReport/

### Upgrade Paths

```
"upgradeTest1": "7.13,5.6.16,6.8.15,7.13.0",  
"upgradeTest2": "7.13,6.8.15,7.13.0",  
"upgradeTest3": "7.13,7.8.1,7.13.0",  
"upgradeTest4": "7.13,7.9.3,7.13.0",  
"upgradeTest5": "7.13,7.10.2,7.13.0",  
"upgradeTest6": "7.13,7.11.2,7.13.0",  
"upgradeTest7": "7.13,7.12.1,7.13.0"
```
### Dashboard Tests 

- **Dashboard tests have two types of failures, the fix will be to adjust the numbers to be at least this number of panels or higher** 

- **Should render visualizations (all paths fail)**

```
Error: retry.try timeout: Error: expected 50 to be above 50
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.greaterThan.Assertion.above (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:317:8)
    at Function.above (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:531:15)
    at /var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest1/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/functional/services/dashboard/expectations.ts:218:46
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

- **Should launch sample data (paths originating from 7.x are failing)**

```
Error: expected 18 to equal 19
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.be.Assertion.equal (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:227:8)
    at Assertion.be (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:69:22)
    at Context.<anonymous> (test/upgrade/apps/dashboard/dashboard_smoke_tests.ts:50:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.apply (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/test/src/functional_test_runner/lib/mocha/wrap_function.js:73:16)
```

### Canvas Tests 

- **Canvas tests have one type of failures, the workspace id is different for the log dashboard on 7.x versions, so the fix is to add an alternate id check** 

- **Logs render (paths originating from 7.x are failing)**

```
Error: retry.try timeout: Error: expected [] to have a length of 57 but got 0
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.length (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:374:8)
    at /var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/upgrade/apps/canvas/canvas_smoke_tests.ts:55:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at runAttempt (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_success.ts:27:15)
    at retryForSuccess (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_success.ts:66:21)
    at Retry.try (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry.ts:32:14)
    at Context.<anonymous> (test/upgrade/apps/canvas/canvas_smoke_tests.ts:51:13)
    at Object.apply (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/test/src/functional_test_runner/lib/mocha/wrap_function.js:73:16)
    at onFailure (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_success.ts:17:9)
    at retryForSuccess (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry_for_success.ts:57:13)
    at Retry.try (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/test/common/services/retry/retry.ts:32:14)
    at Context.<anonymous> (test/upgrade/apps/canvas/canvas_smoke_tests.ts:51:13)
```

### Maps Tests

- **Maps tests is failing marginally with the screenshot diff, this is a known product issue, the fix is to make the tolerance slightly more** _(Side note: may convert these to Percy to compare results side by side)_

- **0.249  (all paths fail, this failure is originating 6.x)**

```

Error: expected 0.024974547511312218 to be below 0.02
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.lessThan.Assertion.below (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:336:8)
    at Function.lessThan (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:531:15)
    at Context.<anonymous> (test/upgrade/apps/maps/maps_smoke_tests.ts:169:43)
    at Object.apply (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest2/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/test/src/functional_test_runner/lib/mocha/wrap_function.js:73:16)
```

- **0.0288 (all paths fail, this failure is originating 7.x)**

```
Error: expected 0.028869485294117647 to be below 0.02
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.lessThan.Assertion.below (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:336:8)
    at Function.lessThan (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:531:15)
    at Context.<anonymous> (test/upgrade/apps/maps/maps_smoke_tests.ts:169:43)
    at Object.apply (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/test/src/functional_test_runner/lib/mocha/wrap_function.js:73:16)
```

### Reporting Tests 

- **Reporting tests are real failures occurring at 2GB RAM, the fix is to increase to 4GB**

- **(These are intermittent, does not appear to be path specific)**

```
Error: Timeout of 360000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest4/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/upgrade/apps/reporting/reporting_smoke_tests.ts)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Error: expected 500 to equal 200
    at Assertion.assert (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest7/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:100:11)
    at Assertion.be.Assertion.equal (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest7/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:227:8)
    at Assertion.be (/var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest7/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/node_modules/@kbn/expect/expect.js:69:22)
    at Object.waitForJobToFinish (test/upgrade/reporting_services.ts:76:29)
    at /var/lib/jenkins/workspace/elastic+estf-cloud-upgrade-tests/JOB/upgradeTest7/TASK/kibana_upgrade_tests/node/ess-testing/ci/upgrade/kibana/build/kibana/x-pack/test/upgrade/reporting_services.ts:82:11
```

**Comment by liza-mae** [comment]
After merging elastic/kibana#100306 and #904 the test results only show 1 reporting failure 

https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/102/testReport/

**Comment by liza-mae** [comment]
The reporting failure is not a test issue, investigating why 4GB isn't enough, also the following has been merged to fix large dashboards: https://github.com/elastic/kibana/issues/87956

**Comment by liza-mae** [comment]
Reporting failure might be related to: https://github.com/elastic/kibana/issues/100461

**Comment by liza-mae** [comment]
Increased Kibana RAM to 8GB fixes the reporting issue.  All tests pass now!

https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-cloud-upgrade-tests/103/testReport/

Closing.

**Comment by liza-mae** [comment]
A subsequent run on 7.13.1 at 8GB RAM for reporting failed, so something else causing the reporting issue.
