### ISSUE TITLE
Stack monitoring Kibana parity tests are failing

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#936]
Version: 7.14 and 7.x

Stack monitoring parity tests are failing for Kibana: 

https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/18/console
https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+7.x+multijob-kibana/558/console

```
04:26:10 TASK [Compare legacy-indexed and metricbeat-indexed documents for parity] ******
04:26:10 fatal: [aithost]: FAILED! => {
04:26:10     "changed": true,
04:26:10     "cmd": "python /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/kibana/docs_compare.py /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/legacy /var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/metricbeat",
04:26:10     "delta": "0:00:00.106392",
04:26:10     "end": "2021-07-13 12:24:57.553722",
04:26:10     "rc": 1,
04:26:10     "start": "2021-07-13 12:24:57.447330"
04:26:10 }
04:26:10 
04:26:10 STDERR:
04:26:10 
04:26:10 ERROR: Found more legacy-indexed document types than metricbeat-indexed document types.
04:26:10                Document types indexed by legacy collection but not by Metricbeat collection: {'kibana_stats', 'kibana_settings'}
04:26:10 Traceback (most recent call last):
04:26:10   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/kibana/docs_compare.py", line 49, in <module>
04:26:10     check_parity(handle_special_cases, allowed_deletions_from_metricbeat_docs_extra=allowed_deletions_from_metricbeat_docs_extra)
04:26:10   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/common/docs_compare_util.py", line 162, in check_parity
04:26:10     metricbeat_doc = get_doc(metricbeat_docs_path, doc_type)
04:26:10   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/playbooks/monitoring/common/docs_compare_util.py", line 66, in get_doc
04:26:10     with open(os.path.join(docs_path, doc_type + ".json")) as f:
04:26:10 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/monitoring//kibana/metricbeat/kibana_stats.json'
```

**Comment by liza-mae** [comment]
7.14 passed today

**Comment by liza-mae** [comment]
https://internal-ci.elastic.co/job/elastic+estf-monitoring-snapshots+7.14+multijob-kibana/29/console

**Comment by liza-mae** [comment]
I noticed other tests are failing at times since it appears with 7.14.0 Kibana can take a bit longer to come, so I thinking adding a longer wait time for this will fix the problem.

**Comment by neptunian** [comment]
@sayden Do you have an idea what could be the problem with these tests failing.  We have a flakey test here where metricbeat with the kibana module enabled sometimes does not send any data.  Legacy collection is working fine.  I tried in [this pr](https://github.com/elastic/elastic-stack-testing/pull/973/files) to keep waiting by recalling the request until I get some hits but it still fails sometimes with no documents returned.

**Comment by pmuellr** [comment]
We're tracking task manager / alerting setting the `unavailable` status, here: https://github.com/elastic/kibana/issues/109095

There doesn't seem to be anything consistent here when we've seen problems.  I've seen it switch from unavailable -> available every 5 seconds.  Still looking into other work-arounds.

Generally speaking, even if alerting / task manager is returning `unavailable`, and thus causing Kibana to say it's `unavailable` and return a 503 from `GET api/status`, Kibana is still operational.  The `GET api/status` call still returns a body which you could use to determine a specific plugin's status.  Of course, if that plugin depends directly or indirectly on task manager or alerting, it will likely also be reporting an `unavailable` status.
