### ISSUE TITLE
Stack monitoring tests are failing on master

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-stack-testing#937]
Version: master

https://internal-ci.elastic.co/view/Stack%20Tests/job/elastic+estf-monitoring-snapshots+master/

- Elasticsearch 
```
23:14:33 ERROR: Found more legacy-indexed document types than metricbeat-indexed document types.
23:14:33                Document types indexed by legacy collection but not by Metricbeat collection: {'ccr_auto_follow_stats',
23:14:33  'cluster_stats',
23:14:33  'enrich_coordinator_stats',
23:14:33  'index_recovery',
23:14:33  'index_stats',
23:14:33  'indices_stats',
23:14:33  'node_stats',
23:14:33  'shards'}
23:14:33 Traceback (most recent call last):
23:14:33   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/playbooks/monitoring/elasticsearch/docs_compare.py", line 133, in <module>
23:14:33     check_parity(handle_special_cases)
23:14:33   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/playbooks/monitoring/common/docs_compare_util.py", line 162, in check_parity
23:14:33     metricbeat_doc = get_doc(metricbeat_docs_path, doc_type)
23:14:33   File "/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/playbooks/monitoring/common/docs_compare_util.py", line 66, in get_doc
23:14:33     with open(os.path.join(docs_path, doc_type + ".json")) as f:
23:14:33 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/jenkins/workspace/elastic+estf-monitoring-snapshots+master+multijob-elasticsearch/monitoring//elasticsearch/metricbeat/shards.json'
```
- Kibana 
```
3:27:20 TASK [Clean out kibana monitoring index] ***************************************
23:27:20 fatal: [aithost]: FAILED! => {
23:27:20     "changed": false,
23:27:20     "content_length": "239",
23:27:20     "content_type": "application/json;charset=utf-8",
23:27:20     "elapsed": 0,
23:27:20     "json": {
23:27:20         "error": {
23:27:20             "reason": "Wildcard expressions or all indices are not allowed",
23:27:20             "root_cause": [
23:27:20                 {
23:27:20                     "reason": "Wildcard expressions or all indices are not allowed",
23:27:20                     "type": "illegal_argument_exception"
23:27:20                 }
23:27:20             ],
23:27:20             "type": "illegal_argument_exception"
23:27:20         },
23:27:20         "status": 400
23:27:20     },
23:27:20     "redirected": false,
23:27:20     "status": 400,
23:27:20     "url": "https://10.0.2.15:9200/.monitoring-kibana-*",
23:27:20     "x_elastic_product": "Elasticsearch"
23:27:20 }
23:27:20 
23:27:20 MSG:
23:27:20 
23:27:20 Status code was 400 and not [200]: HTTP Error 400: Bad Request
23:27:20 
```
- Logsash 
```
23:36:13 TASK [Clean out logstash monitoring index] *************************************
23:36:13 fatal: [aithost]: FAILED! => {
23:36:13     "changed": false,
23:36:13     "content_length": "239",
23:36:13     "content_type": "application/json;charset=utf-8",
23:36:13     "elapsed": 0,
23:36:13     "json": {
23:36:13         "error": {
23:36:13             "reason": "Wildcard expressions or all indices are not allowed",
23:36:13             "root_cause": [
23:36:13                 {
23:36:13                     "reason": "Wildcard expressions or all indices are not allowed",
23:36:13                     "type": "illegal_argument_exception"
23:36:13                 }
23:36:13             ],
23:36:13             "type": "illegal_argument_exception"
23:36:13         },
23:36:13         "status": 400
23:36:13     },
23:36:13     "redirected": false,
23:36:13     "status": 400,
23:36:13     "url": "https://10.0.2.15:9200/.monitoring-logstash-*",
23:36:13     "x_elastic_product": "Elasticsearch"
23:36:13 }
23:36:13 
23:36:13 MSG:
23:36:13 
23:36:13 Status code was 400 and not [200]: HTTP Error 400: Bad Request
```
- Beats
```
23:30:52 TASK [Clean out beats monitoring index] ****************************************
23:30:52 fatal: [aithost]: FAILED! => {
23:30:53     "changed": false,
23:30:53     "content_length": "239",
23:30:53     "content_type": "application/json;charset=utf-8",
23:30:53     "elapsed": 0,
23:30:53     "json": {
23:30:53         "error": {
23:30:53             "reason": "Wildcard expressions or all indices are not allowed",
23:30:53             "root_cause": [
23:30:53                 {
23:30:53                     "reason": "Wildcard expressions or all indices are not allowed",
23:30:53                     "type": "illegal_argument_exception"
23:30:53                 }
23:30:53             ],
23:30:53             "type": "illegal_argument_exception"
23:30:53         },
23:30:53         "status": 400
23:30:53     },
23:30:53     "redirected": false,
23:30:53     "status": 400,
23:30:53     "url": "https://10.0.2.15:9200/.monitoring-beats-*",
23:30:53     "x_elastic_product": "Elasticsearch"
23:30:53 }
23:30:53 
23:30:53 MSG:
23:30:53 
23:30:53 Status code was 400 and not [200]: HTTP Error 400: Bad Request
23:30:53 
```

```

**Comment by neptunian** [comment]
These will not pass due to master/8.0.0 no longer creating the `.monitoring-*` indices with monitoring with metricbeat, rather only the metricbeat index.  For now, we should remove them as we don't expect parity between these two, but we may add them back later depending if we decided to keep or remove`xpack.enabled`.

More info: https://github.com/elastic/beats/pull/24427

**Comment by liza-mae** [comment]
Per [slack convo](https://elastic.slack.com/archives/CEFAY0599/p1641405388271200).  Reopening to investigate re-adding these tests back, cc: @klacabane @matschaffer

**Comment by matschaffer** [comment]
Thanks @liza-mae - I'd also lite to get your thoughts on using elastic-stack-testing to help execute https://docs.google.com/spreadsheets/d/1xDX3atdW74Wcso28-BAUMD0fWi9lpUXMxnh5K0aSpRA/edit#gid=1361223087

As far as I know we have 5 collection modes: Internal via ES, Internal direct (I think only logstash), Metricbeat standalone, Metricbeat standalone on cloud, Agent

It'd be great to have something that flags if the latest snapshot causes failures on any of them.

**Comment by liza-mae** [comment]
Thanks @matschaffer yes I will look over the test plan and gather some thoughts on approach, we can discuss when you are ready.

**Comment by liza-mae** [comment]
Per conversation with @matschaffer submitted re-enabling these tests on CI, they will still fail someone needs to fix them.

**Comment by matschaffer** [comment]
Thanks @liza-mae - I'm working on seeing if I can get these passing (and hopefully use ESTF for a stack monitoring smoke test) as part of our "ON" week this week.

**Comment by liza-mae** [comment]
Closing, these tests will be removed: https://github.com/elastic/elastic-stack-testing/issues/1153
